---
abstract: 'Provide the stuff missing in List::Util'
author:
  - 'Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>'
build_requires:
  Test::More: 0.42
configure_requires:
  ExtUtils::CBuilder: 0.27
  ExtUtils::MakeMaker: 6.52
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-MoreUtils
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0.82
  perl: 5.00503
version: 0.33_006
